# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('message', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
